/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void textfield1_change1(GTextField source, GEvent event) { //_CODE_:txtAGE:666163:
} //_CODE_:txtAGE:666163:

public void btnSubmitClick(GButton source, GEvent event) { //_CODE_:btnSubmit:499834:
  String age = txtAGE.getText().trim();
  if(age.equals("")){
    lblError.setText("You did not enter an age.");
  }
  if(age.contains(" ")){
   lblError.setText("Your format entered was incorrect"); 
  }
  else{
      boolean correct = age.matches("-?[0-9]+");
      if(correct){
        setAgeAndHeartRateRange(int(age));
        setRestingScreen();
      }
      else{
         lblError.setText("You entered letters.");
      }
  }
  
  
  
  
} //_CODE_:btnSubmit:499834:

public void btnStartAVGClick(GButton source, GEvent event) { //_CODE_:btnStartAVG:359934:
  startTracking();
  btnStartAVG.setEnabled(false);
} //_CODE_:btnStartAVG:359934:

public void btnWorkingClick(GButton source, GEvent event) { //_CODE_:btnWorkingOut:992550:
  setFitnessDuringScreen();
} //_CODE_:btnWorkingOut:992550:

public void btnStressedClick(GButton source, GEvent event) { //_CODE_:btnStress:848333:
   setStressScreen();
} //_CODE_:btnStress:848333:

public void btnStartWorkoutClick(GButton source, GEvent event) { //_CODE_:btnStartWorkOut:724670:
  updateFitnessScreen(true);
} //_CODE_:btnStartWorkOut:724670:

public void btnStopWorkOutClick(GButton source, GEvent event) { //_CODE_:btnStopWorkOut:505365:
   updateFitnessScreen(false);
} //_CODE_:btnStopWorkOut:505365:

public void btnStartStressedClick(GButton source, GEvent event) { //_CODE_:btnStartStressed:662170:
   updateStressScreen(true);
} //_CODE_:btnStartStressed:662170:

public void btnStopCheckingClick(GButton source, GEvent event) { //_CODE_:btnStopCheckingStress:742802:
  updateStressScreen(false);
} //_CODE_:btnStopCheckingStress:742802:

public void btnGoHomeWorkoutClick(GButton source, GEvent event) { //_CODE_:btnHomeWorkoutDuring:894965:
  setHomeScreen("Working Out");
} //_CODE_:btnHomeWorkoutDuring:894965:

public void btnWorkoutAfterHomeClick(GButton source, GEvent event) { //_CODE_:btnWorkoutAfterHome:429775:
  setHomeScreen("Workout Results");
} //_CODE_:btnWorkoutAfterHome:429775:

public void btnStressHomeOnClick(GButton source, GEvent event) { //_CODE_:btnStressHome:495499:
  setHomeScreen("Stress Check");
} //_CODE_:btnStressHome:495499:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  txtAGE = new GTextField(this, 203, 154, 128, 36, G4P.SCROLLBARS_NONE);
  txtAGE.setPromptText("Enter your age");
  txtAGE.setOpaque(true);
  txtAGE.addEventHandler(this, "textfield1_change1");
  lblAge = new GLabel(this, 150, 153, 52, 36);
  lblAge.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  lblAge.setText("AGE:");
  lblAge.setOpaque(false);
  btnSubmit = new GButton(this, 150, 202, 180, 36);
  btnSubmit.setText("Next");
  btnSubmit.addEventHandler(this, "btnSubmitClick");
  lblError = new GLabel(this, 130, 118, 180, 27);
  lblError.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  lblError.setOpaque(false);
  lblRestingHeart = new GLabel(this, 130, 37, 218, 41);
  lblRestingHeart.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  lblRestingHeart.setText("Lets calculate your resting heart rate!");
  lblRestingHeart.setOpaque(false);
  lblPlaceFingerOn = new GLabel(this, 99, 80, 276, 34);
  lblPlaceFingerOn.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  lblPlaceFingerOn.setText("Place your finger on the sensor and click start!");
  lblPlaceFingerOn.setOpaque(false);
  btnStartAVG = new GButton(this, 124, 265, 226, 42);
  btnStartAVG.setText("START");
  btnStartAVG.setLocalColorScheme(GCScheme.CENTER);
  btnStartAVG.addEventHandler(this, "btnStartAVGClick");
  lblCurrBPM = new GLabel(this, 33, 116, 117, 27);
  lblCurrBPM.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  lblCurrBPM.setText("Current BPM");
  lblCurrBPM.setOpaque(false);
  lblTimeLeft = new GLabel(this, 126, 221, 129, 38);
  lblTimeLeft.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  lblTimeLeft.setText("Time Left:");
  lblTimeLeft.setOpaque(false);
  lblSEC = new GLabel(this, 258, 222, 75, 38);
  lblSEC.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  lblSEC.setText("30 seconds");
  lblSEC.setOpaque(false);
  lblBPM = new GLabel(this, 33, 144, 117, 80);
  lblBPM.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  lblBPM.setText("0");
  lblBPM.setOpaque(false);
  lblCURROx = new GLabel(this, 177, 117, 117, 27);
  lblCURROx.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  lblCURROx.setText("Current Oxygen");
  lblCURROx.setOpaque(false);
  lblOX = new GLabel(this, 177, 145, 117, 80);
  lblOX.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  lblOX.setText("0");
  lblOX.setOpaque(false);
  lblCURRConf = new GLabel(this, 325, 117, 117, 27);
  lblCURRConf.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  lblCURRConf.setText("Confidence");
  lblCURRConf.setOpaque(false);
  lblConfidence = new GLabel(this, 325, 144, 117, 80);
  lblConfidence.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  lblConfidence.setText("0");
  lblConfidence.setOpaque(false);
  lblAverageHR = new GLabel(this, 43, 9, 190, 20);
  lblAverageHR.setTextAlign(GAlign.RIGHT, GAlign.MIDDLE);
  lblAverageHR.setText("Average Resting Heart Rate:");
  lblAverageHR.setOpaque(false);
  lblAverageOX = new GLabel(this, 43, 34, 190, 20);
  lblAverageOX.setTextAlign(GAlign.RIGHT, GAlign.MIDDLE);
  lblAverageOX.setText("Average Oxygen Level:");
  lblAverageOX.setOpaque(false);
  lblAverageConf = new GLabel(this, 43, 59, 190, 20);
  lblAverageConf.setTextAlign(GAlign.RIGHT, GAlign.MIDDLE);
  lblAverageConf.setText("Average Confidence:");
  lblAverageConf.setOpaque(false);
  lblAverageRHV = new GLabel(this, 239, 10, 80, 20);
  lblAverageRHV.setText("2");
  lblAverageRHV.setOpaque(false);
  lblConfV = new GLabel(this, 237, 59, 80, 20);
  lblConfV.setText("2");
  lblConfV.setOpaque(false);
  lblOXV = new GLabel(this, 238, 35, 80, 20);
  lblOXV.setText("3");
  lblOXV.setTextBold();
  lblOXV.setOpaque(false);
  btnWorkingOut = new GButton(this, 97, 100, 298, 99);
  btnWorkingOut.setText("Working out?");
  btnWorkingOut.setLocalColorScheme(GCScheme.ORANGE_SCHEME);
  btnWorkingOut.addEventHandler(this, "btnWorkingClick");
  btnStress = new GButton(this, 100, 214, 293, 114);
  btnStress.setText("Are you stressed?");
  btnStress.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  btnStress.addEventHandler(this, "btnStressedClick");
  btnStartWorkOut = new GButton(this, 102, 313, 288, 65);
  btnStartWorkOut.setText("Start Workout");
  btnStartWorkOut.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  btnStartWorkOut.addEventHandler(this, "btnStartWorkoutClick");
  btnStopWorkOut = new GButton(this, 102, 387, 288, 65);
  btnStopWorkOut.setText("Stop Workout");
  btnStopWorkOut.setLocalColorScheme(GCScheme.RED_SCHEME);
  btnStopWorkOut.addEventHandler(this, "btnStopWorkOutClick");
  lblWorkOutTime = new GLabel(this, 151, 101, 100, 46);
  lblWorkOutTime.setTextAlign(GAlign.RIGHT, GAlign.MIDDLE);
  lblWorkOutTime.setText("Workout Time:");
  lblWorkOutTime.setOpaque(false);
  lblCurrWorkOutTime = new GLabel(this, 251, 113, 80, 20);
  lblCurrWorkOutTime.setText("0 seconds");
  lblCurrWorkOutTime.setOpaque(false);
  lblWorkOutCurrBPM = new GLabel(this, 177, 155, 147, 33);
  lblWorkOutCurrBPM.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  lblWorkOutCurrBPM.setText("Current BPM:");
  lblWorkOutCurrBPM.setOpaque(false);
  lblWorkoutBPMV = new GLabel(this, 177, 188, 147, 80);
  lblWorkoutBPMV.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  lblWorkoutBPMV.setText("  ");
  lblWorkoutBPMV.setOpaque(false);
  lblWorkoutLevel = new GLabel(this, 44, 272, 128, 28);
  lblWorkoutLevel.setTextAlign(GAlign.RIGHT, GAlign.MIDDLE);
  lblWorkoutLevel.setText("Cardio Zone:");
  lblWorkoutLevel.setOpaque(false);
  lblCardioZoneVal = new GLabel(this, 175, 272, 276, 30);
  lblCardioZoneVal.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  lblCardioZoneVal.setOpaque(false);
  lblStressedCurrentBPM = new GLabel(this, 177, 155, 147, 33);
  lblStressedCurrentBPM.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  lblStressedCurrentBPM.setText("Current BPM");
  lblStressedCurrentBPM.setOpaque(false);
  lblStessedBPMV = new GLabel(this, 176, 188, 148, 80);
  lblStessedBPMV.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  lblStessedBPMV.setOpaque(false);
  btnStartStressed = new GButton(this, 100, 300, 294, 77);
  btnStartStressed.setText("Start Checking");
  btnStartStressed.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  btnStartStressed.addEventHandler(this, "btnStartStressedClick");
  lblStressedInfo = new GLabel(this, 81, 10, 332, 65);
  lblStressedInfo.setTextAlign(GAlign.LEFT, GAlign.LEFT);
  lblStressedInfo.setText("While checking to see if you are stressed we will check your heart rate.");
  lblStressedInfo.setOpaque(false);
  lblStessStatus = new GLabel(this, 77, 272, 96, 20);
  lblStessStatus.setTextAlign(GAlign.RIGHT, GAlign.MIDDLE);
  lblStessStatus.setText("Stress Status: ");
  lblStessStatus.setOpaque(false);
  lblStressStatusV = new GLabel(this, 175, 272, 232, 27);
  lblStressStatusV.setOpaque(false);
  lblStressTime = new GLabel(this, 131, 101, 120, 47);
  lblStressTime.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  lblStressTime.setText("Checking stress for");
  lblStressTime.setOpaque(false);
  lblCurrentStressTimeV = new GLabel(this, 251, 113, 80, 20);
  lblCurrentStressTimeV.setText("0 seconds");
  lblCurrentStressTimeV.setOpaque(false);
  btnStopCheckingStress = new GButton(this, 102, 386, 288, 71);
  btnStopCheckingStress.setText("Stop Checking");
  btnStopCheckingStress.setLocalColorScheme(GCScheme.RED_SCHEME);
  btnStopCheckingStress.addEventHandler(this, "btnStopCheckingClick");
  lblDidntWorkout = new GLabel(this, 98, 98, 299, 67);
  lblDidntWorkout.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  lblDidntWorkout.setText("You didn't workout long enough to measure any levels. The graph below will have little detail.");
  lblDidntWorkout.setOpaque(false);
  btnHomeWorkoutDuring = new GButton(this, 5, 5, 66, 30);
  btnHomeWorkoutDuring.setText("Home");
  btnHomeWorkoutDuring.addEventHandler(this, "btnGoHomeWorkoutClick");
  btnWorkoutAfterHome = new GButton(this, 5, 5, 66, 30);
  btnWorkoutAfterHome.setText("Home");
  btnWorkoutAfterHome.addEventHandler(this, "btnWorkoutAfterHomeClick");
  btnStressHome = new GButton(this, 5, 5, 66, 30);
  btnStressHome.setText("Home");
  btnStressHome.addEventHandler(this, "btnStressHomeOnClick");
  lblBetweenBeats = new GLabel(this, 44, 79, 188, 20);
  lblBetweenBeats.setTextAlign(GAlign.RIGHT, GAlign.LEFT);
  lblBetweenBeats.setText("Time Between Beats:");
  lblBetweenBeats.setOpaque(false);
  lblTimeBetweenBeatsV = new GLabel(this, 235, 79, 88, 20);
  lblTimeBetweenBeatsV.setText("   ");
  lblTimeBetweenBeatsV.setOpaque(false);
}

// Variable declarations 
// autogenerated do not edit
GTextField txtAGE; 
GLabel lblAge; 
GButton btnSubmit; 
GLabel lblError; 
GLabel lblRestingHeart; 
GLabel lblPlaceFingerOn; 
GButton btnStartAVG; 
GLabel lblCurrBPM; 
GLabel lblTimeLeft; 
GLabel lblSEC; 
GLabel lblBPM; 
GLabel lblCURROx; 
GLabel lblOX; 
GLabel lblCURRConf; 
GLabel lblConfidence; 
GLabel lblAverageHR; 
GLabel lblAverageOX; 
GLabel lblAverageConf; 
GLabel lblAverageRHV; 
GLabel lblConfV; 
GLabel lblOXV; 
GButton btnWorkingOut; 
GButton btnStress; 
GButton btnStartWorkOut; 
GButton btnStopWorkOut; 
GLabel lblWorkOutTime; 
GLabel lblCurrWorkOutTime; 
GLabel lblWorkOutCurrBPM; 
GLabel lblWorkoutBPMV; 
GLabel lblWorkoutLevel; 
GLabel lblCardioZoneVal; 
GLabel lblStressedCurrentBPM; 
GLabel lblStessedBPMV; 
GButton btnStartStressed; 
GLabel lblStressedInfo; 
GLabel lblStessStatus; 
GLabel lblStressStatusV; 
GLabel lblStressTime; 
GLabel lblCurrentStressTimeV; 
GButton btnStopCheckingStress; 
GLabel lblDidntWorkout; 
GButton btnHomeWorkoutDuring; 
GButton btnWorkoutAfterHome; 
GButton btnStressHome; 
GLabel lblBetweenBeats; 
GLabel lblTimeBetweenBeatsV; 
